stages:          # List of stages for jobs, and their order of execution
  - python27
  - python36
  - python37
  - python38
  - python39
  - python310
  - python311
  - full_test

.test-job:
  needs: []
  timeout: 10m
  retry: 2
  script:
    - |
      cat <<EOT >> config.yaml
      channelid: '$CHANNEL_ID'
      bottoken: '$BOT_TOKEN'
      EOT
    - pip install -r requirements.txt -r requirements-dev.txt OctoPrint==$OCTOVER
    - python setup.py bdist_wheel
    - pip install dist/*.whl
    - FAST_TEST=1 pytest

.install-only:
  needs: []
  timeout: 10m
  retry: 2
  script:
    - pip install -r requirements.txt OctoPrint==$OCTOVER
    - python setup.py bdist_wheel
    - pip install dist/*.whl

python27-installonly:
  stage: python27
  parallel:
    matrix:
      - OCTOVER: [ '1.7.3' ]
  extends: .install-only
  image: python:2.7

python36-installonly:
  stage: python36
  parallel:
    matrix:
      - OCTOVER: [ '1.7.3' ]
  extends: .install-only
  image: python:3.6

python37:
  stage: python37
  parallel:
    matrix:
      - OCTOVER: [ '1.7.3', '1.8.7' ]
  extends: .test-job
  image: python:3.7

python38:
  stage: python38
  parallel:
    matrix:
      - OCTOVER: [ '1.7.3', '1.8.7', '1.9.2' ]
  extends: .test-job
  image: python:3.8

python39:
  stage: python39
  parallel:
    matrix:
      - OCTOVER: [ '1.7.3', '1.8.7', '1.9.2' ]
  extends: .test-job
  image: python:3.9

python310:
  stage: python310
  parallel:
    matrix:
      - OCTOVER: [ '1.9.2' ]
  extends: .test-job
  image: python:3.10

python311:
  stage: python311
  parallel:
    matrix:
      - OCTOVER: [ '1.9.2' ]
  extends: .test-job
  image: python:3.11

full_test:
  stage: python311
  image: python:3.11
  timeout: 20m
  retry: 2
  script:
    - |
      cat <<EOT >> config.yaml
      channelid: '$CHANNEL_ID'
      bottoken: '$BOT_TOKEN'
      EOT
    - pip install -r requirements.txt -r requirements-dev.txt OctoPrint=='1.9.2'
    - python setup.py bdist_wheel
    - pip install dist/*.whl
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
