stages:          # List of stages for jobs, and their order of execution
  - python36
  - python37
  - python38
  - python39
  - python310

.test-job:
  needs: []
  timeout: 10m
  retry: 2
  script:
    - |
      cat <<EOT >> config.yaml
      channelid: '$CHANNEL_ID'
      bottoken: '$BOT_TOKEN'
      EOT
    - pip install -r requirements.txt -r requirements-dev.txt OctoPrint==$OCTOVER
    - python setup.py bdist_wheel
    - pip install dist/*.whl
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

python38:
  stage: python38
  parallel:
    matrix:
      - OCTOVER: [ '1.7.3', '1.8.7', '1.9.0rc5' ]
  extends: .test-job
  image: python:3.8

python39:
  stage: python39
  parallel:
    matrix:
      - OCTOVER: [ '1.7.3', '1.8.7', '1.9.0rc5' ]
  extends: .test-job
  image: python:3.9

python310:
  stage: python310
  parallel:
    matrix:
      - OCTOVER: [ '1.7.3', '1.8.7', '1.9.0rc5' ]
  extends: .test-job
  image: python:3.10
