// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoConfig.proto

package com.cross.beaglesightlibs;

public final class ProtoConfig {
  private ProtoConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:beaglesightlibs.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string bowname = 1;</code>
     */
    boolean hasBowname();
    /**
     * <code>required string bowname = 1;</code>
     */
    java.lang.String getBowname();
    /**
     * <code>required string bowname = 1;</code>
     */
    com.google.protobuf.ByteString
        getBownameBytes();

    /**
     * <code>optional string bowfilepath = 2;</code>
     */
    boolean hasBowfilepath();
    /**
     * <code>optional string bowfilepath = 2;</code>
     */
    java.lang.String getBowfilepath();
    /**
     * <code>optional string bowfilepath = 2;</code>
     */
    com.google.protobuf.ByteString
        getBowfilepathBytes();

    /**
     * <code>optional string bowdescription = 3;</code>
     */
    boolean hasBowdescription();
    /**
     * <code>optional string bowdescription = 3;</code>
     */
    java.lang.String getBowdescription();
    /**
     * <code>optional string bowdescription = 3;</code>
     */
    com.google.protobuf.ByteString
        getBowdescriptionBytes();

    /**
     * <code>required uint32 method = 4;</code>
     */
    boolean hasMethod();
    /**
     * <code>required uint32 method = 4;</code>
     */
    int getMethod();

    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    java.util.List<com.cross.beaglesightlibs.ProtoConfig.Config.Position> 
        getPositionArrayList();
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    com.cross.beaglesightlibs.ProtoConfig.Config.Position getPositionArray(int index);
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    int getPositionArrayCount();
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    java.util.List<? extends com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder> 
        getPositionArrayOrBuilderList();
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder getPositionArrayOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code beaglesightlibs.Config}
   */
  public static final class Config extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:beaglesightlibs.Config)
      ConfigOrBuilder {
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Config(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Config defaultInstance;
    public static Config getDefaultInstance() {
      return defaultInstance;
    }

    public Config getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              bowname_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              bowfilepath_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              bowdescription_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              method_ = input.readUInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                positionArray_ = new java.util.ArrayList<com.cross.beaglesightlibs.ProtoConfig.Config.Position>();
                mutable_bitField0_ |= 0x00000010;
              }
              positionArray_.add(input.readMessage(com.cross.beaglesightlibs.ProtoConfig.Config.Position.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          positionArray_ = java.util.Collections.unmodifiableList(positionArray_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cross.beaglesightlibs.ProtoConfig.Config.class, com.cross.beaglesightlibs.ProtoConfig.Config.Builder.class);
    }

    public static com.google.protobuf.Parser<Config> PARSER =
        new com.google.protobuf.AbstractParser<Config>() {
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Config(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    public interface PositionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:beaglesightlibs.Config.Position)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string distance = 1;</code>
       */
      boolean hasDistance();
      /**
       * <code>required string distance = 1;</code>
       */
      java.lang.String getDistance();
      /**
       * <code>required string distance = 1;</code>
       */
      com.google.protobuf.ByteString
          getDistanceBytes();

      /**
       * <code>required string posvalue = 2;</code>
       */
      boolean hasPosvalue();
      /**
       * <code>required string posvalue = 2;</code>
       */
      java.lang.String getPosvalue();
      /**
       * <code>required string posvalue = 2;</code>
       */
      com.google.protobuf.ByteString
          getPosvalueBytes();
    }
    /**
     * Protobuf type {@code beaglesightlibs.Config.Position}
     */
    public static final class Position extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:beaglesightlibs.Config.Position)
        PositionOrBuilder {
      // Use Position.newBuilder() to construct.
      private Position(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Position(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Position defaultInstance;
      public static Position getDefaultInstance() {
        return defaultInstance;
      }

      public Position getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Position(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                distance_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                posvalue_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_Position_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cross.beaglesightlibs.ProtoConfig.Config.Position.class, com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder.class);
      }

      public static com.google.protobuf.Parser<Position> PARSER =
          new com.google.protobuf.AbstractParser<Position>() {
        public Position parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Position(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Position> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int DISTANCE_FIELD_NUMBER = 1;
      private java.lang.Object distance_;
      /**
       * <code>required string distance = 1;</code>
       */
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string distance = 1;</code>
       */
      public java.lang.String getDistance() {
        java.lang.Object ref = distance_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            distance_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string distance = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDistanceBytes() {
        java.lang.Object ref = distance_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          distance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int POSVALUE_FIELD_NUMBER = 2;
      private java.lang.Object posvalue_;
      /**
       * <code>required string posvalue = 2;</code>
       */
      public boolean hasPosvalue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string posvalue = 2;</code>
       */
      public java.lang.String getPosvalue() {
        java.lang.Object ref = posvalue_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            posvalue_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string posvalue = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPosvalueBytes() {
        java.lang.Object ref = posvalue_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          posvalue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        distance_ = "";
        posvalue_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDistance()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPosvalue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getDistanceBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPosvalueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getDistanceBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPosvalueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.cross.beaglesightlibs.ProtoConfig.Config.Position parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.cross.beaglesightlibs.ProtoConfig.Config.Position prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code beaglesightlibs.Config.Position}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:beaglesightlibs.Config.Position)
          com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_Position_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_Position_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.cross.beaglesightlibs.ProtoConfig.Config.Position.class, com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder.class);
        }

        // Construct using com.cross.beaglesightlibs.ProtoConfig.Config.Position.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          distance_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          posvalue_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_Position_descriptor;
        }

        public com.cross.beaglesightlibs.ProtoConfig.Config.Position getDefaultInstanceForType() {
          return com.cross.beaglesightlibs.ProtoConfig.Config.Position.getDefaultInstance();
        }

        public com.cross.beaglesightlibs.ProtoConfig.Config.Position build() {
          com.cross.beaglesightlibs.ProtoConfig.Config.Position result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.cross.beaglesightlibs.ProtoConfig.Config.Position buildPartial() {
          com.cross.beaglesightlibs.ProtoConfig.Config.Position result = new com.cross.beaglesightlibs.ProtoConfig.Config.Position(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.distance_ = distance_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.posvalue_ = posvalue_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cross.beaglesightlibs.ProtoConfig.Config.Position) {
            return mergeFrom((com.cross.beaglesightlibs.ProtoConfig.Config.Position)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.cross.beaglesightlibs.ProtoConfig.Config.Position other) {
          if (other == com.cross.beaglesightlibs.ProtoConfig.Config.Position.getDefaultInstance()) return this;
          if (other.hasDistance()) {
            bitField0_ |= 0x00000001;
            distance_ = other.distance_;
            onChanged();
          }
          if (other.hasPosvalue()) {
            bitField0_ |= 0x00000002;
            posvalue_ = other.posvalue_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasDistance()) {
            
            return false;
          }
          if (!hasPosvalue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.cross.beaglesightlibs.ProtoConfig.Config.Position parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.cross.beaglesightlibs.ProtoConfig.Config.Position) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object distance_ = "";
        /**
         * <code>required string distance = 1;</code>
         */
        public boolean hasDistance() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string distance = 1;</code>
         */
        public java.lang.String getDistance() {
          java.lang.Object ref = distance_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              distance_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string distance = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDistanceBytes() {
          java.lang.Object ref = distance_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            distance_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string distance = 1;</code>
         */
        public Builder setDistance(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          distance_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string distance = 1;</code>
         */
        public Builder clearDistance() {
          bitField0_ = (bitField0_ & ~0x00000001);
          distance_ = getDefaultInstance().getDistance();
          onChanged();
          return this;
        }
        /**
         * <code>required string distance = 1;</code>
         */
        public Builder setDistanceBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          distance_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object posvalue_ = "";
        /**
         * <code>required string posvalue = 2;</code>
         */
        public boolean hasPosvalue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string posvalue = 2;</code>
         */
        public java.lang.String getPosvalue() {
          java.lang.Object ref = posvalue_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              posvalue_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string posvalue = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPosvalueBytes() {
          java.lang.Object ref = posvalue_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            posvalue_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string posvalue = 2;</code>
         */
        public Builder setPosvalue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          posvalue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string posvalue = 2;</code>
         */
        public Builder clearPosvalue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          posvalue_ = getDefaultInstance().getPosvalue();
          onChanged();
          return this;
        }
        /**
         * <code>required string posvalue = 2;</code>
         */
        public Builder setPosvalueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          posvalue_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:beaglesightlibs.Config.Position)
      }

      static {
        defaultInstance = new Position(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:beaglesightlibs.Config.Position)
    }

    private int bitField0_;
    public static final int BOWNAME_FIELD_NUMBER = 1;
    private java.lang.Object bowname_;
    /**
     * <code>required string bowname = 1;</code>
     */
    public boolean hasBowname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string bowname = 1;</code>
     */
    public java.lang.String getBowname() {
      java.lang.Object ref = bowname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bowname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bowname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBownameBytes() {
      java.lang.Object ref = bowname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bowname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOWFILEPATH_FIELD_NUMBER = 2;
    private java.lang.Object bowfilepath_;
    /**
     * <code>optional string bowfilepath = 2;</code>
     */
    public boolean hasBowfilepath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string bowfilepath = 2;</code>
     */
    public java.lang.String getBowfilepath() {
      java.lang.Object ref = bowfilepath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bowfilepath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bowfilepath = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBowfilepathBytes() {
      java.lang.Object ref = bowfilepath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bowfilepath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOWDESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object bowdescription_;
    /**
     * <code>optional string bowdescription = 3;</code>
     */
    public boolean hasBowdescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string bowdescription = 3;</code>
     */
    public java.lang.String getBowdescription() {
      java.lang.Object ref = bowdescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bowdescription_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bowdescription = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBowdescriptionBytes() {
      java.lang.Object ref = bowdescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bowdescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 4;
    private int method_;
    /**
     * <code>required uint32 method = 4;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 method = 4;</code>
     */
    public int getMethod() {
      return method_;
    }

    public static final int POSITIONARRAY_FIELD_NUMBER = 5;
    private java.util.List<com.cross.beaglesightlibs.ProtoConfig.Config.Position> positionArray_;
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    public java.util.List<com.cross.beaglesightlibs.ProtoConfig.Config.Position> getPositionArrayList() {
      return positionArray_;
    }
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    public java.util.List<? extends com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder> 
        getPositionArrayOrBuilderList() {
      return positionArray_;
    }
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    public int getPositionArrayCount() {
      return positionArray_.size();
    }
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    public com.cross.beaglesightlibs.ProtoConfig.Config.Position getPositionArray(int index) {
      return positionArray_.get(index);
    }
    /**
     * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
     */
    public com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder getPositionArrayOrBuilder(
        int index) {
      return positionArray_.get(index);
    }

    private void initFields() {
      bowname_ = "";
      bowfilepath_ = "";
      bowdescription_ = "";
      method_ = 0;
      positionArray_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBowname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPositionArrayCount(); i++) {
        if (!getPositionArray(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBownameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBowfilepathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBowdescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, method_);
      }
      for (int i = 0; i < positionArray_.size(); i++) {
        output.writeMessage(5, positionArray_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBownameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBowfilepathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBowdescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, method_);
      }
      for (int i = 0; i < positionArray_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, positionArray_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cross.beaglesightlibs.ProtoConfig.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cross.beaglesightlibs.ProtoConfig.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cross.beaglesightlibs.ProtoConfig.Config prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code beaglesightlibs.Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:beaglesightlibs.Config)
        com.cross.beaglesightlibs.ProtoConfig.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cross.beaglesightlibs.ProtoConfig.Config.class, com.cross.beaglesightlibs.ProtoConfig.Config.Builder.class);
      }

      // Construct using com.cross.beaglesightlibs.ProtoConfig.Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPositionArrayFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bowname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        bowfilepath_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        bowdescription_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        method_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (positionArrayBuilder_ == null) {
          positionArray_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          positionArrayBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cross.beaglesightlibs.ProtoConfig.internal_static_beaglesightlibs_Config_descriptor;
      }

      public com.cross.beaglesightlibs.ProtoConfig.Config getDefaultInstanceForType() {
        return com.cross.beaglesightlibs.ProtoConfig.Config.getDefaultInstance();
      }

      public com.cross.beaglesightlibs.ProtoConfig.Config build() {
        com.cross.beaglesightlibs.ProtoConfig.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cross.beaglesightlibs.ProtoConfig.Config buildPartial() {
        com.cross.beaglesightlibs.ProtoConfig.Config result = new com.cross.beaglesightlibs.ProtoConfig.Config(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bowname_ = bowname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bowfilepath_ = bowfilepath_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bowdescription_ = bowdescription_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.method_ = method_;
        if (positionArrayBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            positionArray_ = java.util.Collections.unmodifiableList(positionArray_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.positionArray_ = positionArray_;
        } else {
          result.positionArray_ = positionArrayBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cross.beaglesightlibs.ProtoConfig.Config) {
          return mergeFrom((com.cross.beaglesightlibs.ProtoConfig.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cross.beaglesightlibs.ProtoConfig.Config other) {
        if (other == com.cross.beaglesightlibs.ProtoConfig.Config.getDefaultInstance()) return this;
        if (other.hasBowname()) {
          bitField0_ |= 0x00000001;
          bowname_ = other.bowname_;
          onChanged();
        }
        if (other.hasBowfilepath()) {
          bitField0_ |= 0x00000002;
          bowfilepath_ = other.bowfilepath_;
          onChanged();
        }
        if (other.hasBowdescription()) {
          bitField0_ |= 0x00000004;
          bowdescription_ = other.bowdescription_;
          onChanged();
        }
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        if (positionArrayBuilder_ == null) {
          if (!other.positionArray_.isEmpty()) {
            if (positionArray_.isEmpty()) {
              positionArray_ = other.positionArray_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensurePositionArrayIsMutable();
              positionArray_.addAll(other.positionArray_);
            }
            onChanged();
          }
        } else {
          if (!other.positionArray_.isEmpty()) {
            if (positionArrayBuilder_.isEmpty()) {
              positionArrayBuilder_.dispose();
              positionArrayBuilder_ = null;
              positionArray_ = other.positionArray_;
              bitField0_ = (bitField0_ & ~0x00000010);
              positionArrayBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPositionArrayFieldBuilder() : null;
            } else {
              positionArrayBuilder_.addAllMessages(other.positionArray_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBowname()) {
          
          return false;
        }
        if (!hasMethod()) {
          
          return false;
        }
        for (int i = 0; i < getPositionArrayCount(); i++) {
          if (!getPositionArray(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cross.beaglesightlibs.ProtoConfig.Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cross.beaglesightlibs.ProtoConfig.Config) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object bowname_ = "";
      /**
       * <code>required string bowname = 1;</code>
       */
      public boolean hasBowname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string bowname = 1;</code>
       */
      public java.lang.String getBowname() {
        java.lang.Object ref = bowname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bowname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bowname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBownameBytes() {
        java.lang.Object ref = bowname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bowname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bowname = 1;</code>
       */
      public Builder setBowname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bowname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bowname = 1;</code>
       */
      public Builder clearBowname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bowname_ = getDefaultInstance().getBowname();
        onChanged();
        return this;
      }
      /**
       * <code>required string bowname = 1;</code>
       */
      public Builder setBownameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bowname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bowfilepath_ = "";
      /**
       * <code>optional string bowfilepath = 2;</code>
       */
      public boolean hasBowfilepath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string bowfilepath = 2;</code>
       */
      public java.lang.String getBowfilepath() {
        java.lang.Object ref = bowfilepath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bowfilepath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bowfilepath = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBowfilepathBytes() {
        java.lang.Object ref = bowfilepath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bowfilepath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bowfilepath = 2;</code>
       */
      public Builder setBowfilepath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bowfilepath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bowfilepath = 2;</code>
       */
      public Builder clearBowfilepath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bowfilepath_ = getDefaultInstance().getBowfilepath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bowfilepath = 2;</code>
       */
      public Builder setBowfilepathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bowfilepath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bowdescription_ = "";
      /**
       * <code>optional string bowdescription = 3;</code>
       */
      public boolean hasBowdescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string bowdescription = 3;</code>
       */
      public java.lang.String getBowdescription() {
        java.lang.Object ref = bowdescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bowdescription_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bowdescription = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBowdescriptionBytes() {
        java.lang.Object ref = bowdescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bowdescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bowdescription = 3;</code>
       */
      public Builder setBowdescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bowdescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bowdescription = 3;</code>
       */
      public Builder clearBowdescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bowdescription_ = getDefaultInstance().getBowdescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bowdescription = 3;</code>
       */
      public Builder setBowdescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bowdescription_ = value;
        onChanged();
        return this;
      }

      private int method_ ;
      /**
       * <code>required uint32 method = 4;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 method = 4;</code>
       */
      public int getMethod() {
        return method_;
      }
      /**
       * <code>required uint32 method = 4;</code>
       */
      public Builder setMethod(int value) {
        bitField0_ |= 0x00000008;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 method = 4;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000008);
        method_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.cross.beaglesightlibs.ProtoConfig.Config.Position> positionArray_ =
        java.util.Collections.emptyList();
      private void ensurePositionArrayIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          positionArray_ = new java.util.ArrayList<com.cross.beaglesightlibs.ProtoConfig.Config.Position>(positionArray_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.cross.beaglesightlibs.ProtoConfig.Config.Position, com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder, com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder> positionArrayBuilder_;

      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public java.util.List<com.cross.beaglesightlibs.ProtoConfig.Config.Position> getPositionArrayList() {
        if (positionArrayBuilder_ == null) {
          return java.util.Collections.unmodifiableList(positionArray_);
        } else {
          return positionArrayBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public int getPositionArrayCount() {
        if (positionArrayBuilder_ == null) {
          return positionArray_.size();
        } else {
          return positionArrayBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public com.cross.beaglesightlibs.ProtoConfig.Config.Position getPositionArray(int index) {
        if (positionArrayBuilder_ == null) {
          return positionArray_.get(index);
        } else {
          return positionArrayBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder setPositionArray(
          int index, com.cross.beaglesightlibs.ProtoConfig.Config.Position value) {
        if (positionArrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionArrayIsMutable();
          positionArray_.set(index, value);
          onChanged();
        } else {
          positionArrayBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder setPositionArray(
          int index, com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder builderForValue) {
        if (positionArrayBuilder_ == null) {
          ensurePositionArrayIsMutable();
          positionArray_.set(index, builderForValue.build());
          onChanged();
        } else {
          positionArrayBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder addPositionArray(com.cross.beaglesightlibs.ProtoConfig.Config.Position value) {
        if (positionArrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionArrayIsMutable();
          positionArray_.add(value);
          onChanged();
        } else {
          positionArrayBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder addPositionArray(
          int index, com.cross.beaglesightlibs.ProtoConfig.Config.Position value) {
        if (positionArrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionArrayIsMutable();
          positionArray_.add(index, value);
          onChanged();
        } else {
          positionArrayBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder addPositionArray(
          com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder builderForValue) {
        if (positionArrayBuilder_ == null) {
          ensurePositionArrayIsMutable();
          positionArray_.add(builderForValue.build());
          onChanged();
        } else {
          positionArrayBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder addPositionArray(
          int index, com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder builderForValue) {
        if (positionArrayBuilder_ == null) {
          ensurePositionArrayIsMutable();
          positionArray_.add(index, builderForValue.build());
          onChanged();
        } else {
          positionArrayBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder addAllPositionArray(
          java.lang.Iterable<? extends com.cross.beaglesightlibs.ProtoConfig.Config.Position> values) {
        if (positionArrayBuilder_ == null) {
          ensurePositionArrayIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, positionArray_);
          onChanged();
        } else {
          positionArrayBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder clearPositionArray() {
        if (positionArrayBuilder_ == null) {
          positionArray_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          positionArrayBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public Builder removePositionArray(int index) {
        if (positionArrayBuilder_ == null) {
          ensurePositionArrayIsMutable();
          positionArray_.remove(index);
          onChanged();
        } else {
          positionArrayBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder getPositionArrayBuilder(
          int index) {
        return getPositionArrayFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder getPositionArrayOrBuilder(
          int index) {
        if (positionArrayBuilder_ == null) {
          return positionArray_.get(index);  } else {
          return positionArrayBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public java.util.List<? extends com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder> 
           getPositionArrayOrBuilderList() {
        if (positionArrayBuilder_ != null) {
          return positionArrayBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(positionArray_);
        }
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder addPositionArrayBuilder() {
        return getPositionArrayFieldBuilder().addBuilder(
            com.cross.beaglesightlibs.ProtoConfig.Config.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder addPositionArrayBuilder(
          int index) {
        return getPositionArrayFieldBuilder().addBuilder(
            index, com.cross.beaglesightlibs.ProtoConfig.Config.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .beaglesightlibs.Config.Position positionArray = 5;</code>
       */
      public java.util.List<com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder> 
           getPositionArrayBuilderList() {
        return getPositionArrayFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cross.beaglesightlibs.ProtoConfig.Config.Position, com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder, com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder> 
          getPositionArrayFieldBuilder() {
        if (positionArrayBuilder_ == null) {
          positionArrayBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.cross.beaglesightlibs.ProtoConfig.Config.Position, com.cross.beaglesightlibs.ProtoConfig.Config.Position.Builder, com.cross.beaglesightlibs.ProtoConfig.Config.PositionOrBuilder>(
                  positionArray_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          positionArray_ = null;
        }
        return positionArrayBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:beaglesightlibs.Config)
    }

    static {
      defaultInstance = new Config(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:beaglesightlibs.Config)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beaglesightlibs_Config_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beaglesightlibs_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beaglesightlibs_Config_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beaglesightlibs_Config_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ProtoConfig.proto\022\017beaglesightlibs\"\277\001\n" +
      "\006Config\022\017\n\007bowname\030\001 \002(\t\022\023\n\013bowfilepath\030" +
      "\002 \001(\t\022\026\n\016bowdescription\030\003 \001(\t\022\016\n\006method\030" +
      "\004 \002(\r\0227\n\rpositionArray\030\005 \003(\0132 .beaglesig" +
      "htlibs.Config.Position\032.\n\010Position\022\020\n\010di" +
      "stance\030\001 \002(\t\022\020\n\010posvalue\030\002 \002(\tB(\n\031com.cr" +
      "oss.beaglesightlibsB\013ProtoConfig"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_beaglesightlibs_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_beaglesightlibs_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beaglesightlibs_Config_descriptor,
        new java.lang.String[] { "Bowname", "Bowfilepath", "Bowdescription", "Method", "PositionArray", });
    internal_static_beaglesightlibs_Config_Position_descriptor =
      internal_static_beaglesightlibs_Config_descriptor.getNestedTypes().get(0);
    internal_static_beaglesightlibs_Config_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beaglesightlibs_Config_Position_descriptor,
        new java.lang.String[] { "Distance", "Posvalue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
