# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x0b\x44iscordShim\"+\n\tProtoFile\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"8\n\tTextField\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06inline\x18\x03 \x01(\x08\"\xa6\x01\n\x0c\x45mbedContent\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05\x63olor\x18\x04 \x01(\x05\x12(\n\x08snapshot\x18\x05 \x01(\x0b\x32\x16.DiscordShim.ProtoFile\x12)\n\ttextfield\x18\x06 \x03(\x0b\x32\x16.DiscordShim.TextField\"\x1c\n\x08Presence\x12\x10\n\x08presence\x18\x01 \x01(\t\"d\n\x08Settings\x12\x12\n\nchannel_id\x18\x01 \x01(\x04\x12\x18\n\x10presence_enabled\x18\x02 \x01(\x08\x12\x12\n\ncycle_time\x18\x03 \x01(\x05\x12\x16\n\x0e\x63ommand_prefix\x18\x04 \x01(\t\"]\n\x07Request\x12\x0c\n\x04user\x18\x01 \x01(\x04\x12\x11\n\x07\x63ommand\x18\x02 \x01(\tH\x00\x12&\n\x04\x66ile\x18\x03 \x01(\x0b\x32\x16.DiscordShim.ProtoFileH\x00\x42\t\n\x07message\"\xbd\x01\n\x08Response\x12*\n\x05\x65mbed\x18\x01 \x01(\x0b\x32\x19.DiscordShim.EmbedContentH\x00\x12)\n\x08presence\x18\x02 \x01(\x0b\x32\x15.DiscordShim.PresenceH\x00\x12&\n\x04\x66ile\x18\x03 \x01(\x0b\x32\x16.DiscordShim.ProtoFileH\x00\x12)\n\x08settings\x18\x04 \x01(\x0b\x32\x15.DiscordShim.SettingsH\x00\x42\x07\n\x05\x66ieldb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOFILE._serialized_start=31
  _PROTOFILE._serialized_end=74
  _TEXTFIELD._serialized_start=76
  _TEXTFIELD._serialized_end=132
  _EMBEDCONTENT._serialized_start=135
  _EMBEDCONTENT._serialized_end=301
  _PRESENCE._serialized_start=303
  _PRESENCE._serialized_end=331
  _SETTINGS._serialized_start=333
  _SETTINGS._serialized_end=433
  _REQUEST._serialized_start=435
  _REQUEST._serialized_end=528
  _RESPONSE._serialized_start=531
  _RESPONSE._serialized_end=720
# @@protoc_insertion_point(module_scope)
