# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"&\n\x04\x46ile\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"4\n\x05\x46ield\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06inline\x18\x03 \x01(\x08\"\x85\x01\n\x0c\x45mbedContent\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05\x63olor\x18\x04 \x01(\x05\x12\x17\n\x08snapshot\x18\x05 \x01(\x0b\x32\x05.File\x12\x19\n\ttextfield\x18\x06 \x03(\x0b\x32\x06.Field\"\x1c\n\x08Presence\x12\x10\n\x08presence\x18\x01 \x01(\t\"t\n\x07\x43ommand\x12\x14\n\x07\x63ommand\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tconnected\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x18\n\x04\x66ile\x18\x03 \x01(\x0b\x32\x05.FileH\x02\x88\x01\x01\x42\n\n\x08_commandB\x0c\n\n_connectedB\x07\n\x05_file\"f\n\x08Response\x12!\n\x05\x65mbed\x18\x01 \x01(\x0b\x32\r.EmbedContentH\x00\x88\x01\x01\x12 \n\x08presence\x18\x02 \x01(\x0b\x32\t.PresenceH\x01\x88\x01\x01\x42\x08\n\x06_embedB\x0b\n\t_presenceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILE._serialized_start=18
  _FILE._serialized_end=56
  _FIELD._serialized_start=58
  _FIELD._serialized_end=110
  _EMBEDCONTENT._serialized_start=113
  _EMBEDCONTENT._serialized_end=246
  _PRESENCE._serialized_start=248
  _PRESENCE._serialized_end=276
  _COMMAND._serialized_start=278
  _COMMAND._serialized_end=394
  _RESPONSE._serialized_start=396
  _RESPONSE._serialized_end=498
# @@protoc_insertion_point(module_scope)
